/**
 * Legacy Shopify → current-site URL redirect map, generated from the GSC
 * legacy-URL research in `will_delete/url-mapping.csv` (dispositions
 * `redirect` and `discontinue` — both have a real target; `discontinue`
 * targets are the nearest category rather than a fake specific match).
 *
 * Keys are `pathname + search` exactly as the old URL appeared (no domain).
 * `/pages/boring-stuff` → `/returns` is intentionally NOT in this map yet:
 * `/returns` is being built separately and doesn't exist, so that one
 * redirect is held until it ships (see url-mapping.csv reason for that row).
 *
 * Consumed by middleware.ts, which issues a real 301.
 */
export const LEGACY_REDIRECTS: Record<string, string> = {
  "/collections": "/products",
  "/collections/1nri": "/products",
  "/collections/1nri-accessories-mainline": "/products?category=Accessories",
  "/collections/1nri-men": "/products?gender=men",
  "/collections/1nri-men-t-shirts": "/products?gender=men&category=Tops&product_type=T-Shirts",
  "/collections/1nri-stpls-women": "/products?category=Tops",
  "/collections/1nri-stpls-women.atom": "/products?category=Tops",
  "/collections/1nri-women": "/products?gender=women",
  "/collections/1nri-women-tshirts-mainline": "/products?gender=women&category=Tops&product_type=T-Shirts",
  "/collections/1nri-women-tshirts-mainline.atom": "/products?gender=women&category=Tops&product_type=T-Shirts",
  "/collections/1nri?page=2": "/products",
  "/collections/all": "/products",
  "/collections/all/women": "/products?gender=women",
  "/collections/all/women.atom": "/products?gender=women",
  "/collections/all/women?page=3": "/products?gender=women",
  "/collections/all/women?page=4": "/products?gender=women",
  "/collections/all?page=2": "/products",
  "/collections/all?page=3": "/products",
  "/collections/best-selling-collection": "/products",
  "/collections/best-selling-collection.atom": "/products",
  "/collections/best-selling-collection?page=1": "/products",
  "/collections/best-selling-collection?page=2": "/products",
  "/collections/intercessory-department": "/products?search=Intercessory",
  "/collections/intercessory-department-1": "/products?search=Intercessory",
  "/collections/intercessory-department-men": "/products?search=Intercessory",
  "/collections/intercessory-department-men.atom": "/products?search=Intercessory",
  "/collections/intercessory-department.atom": "/products?search=Intercessory",
  "/collections/new-collection": "/products",
  "/collections/new-collection.atom": "/products",
  "/collections/new-collection?page=2": "/products",
  "/collections/shirts": "/products?category=Tops&product_type=Shirts",
  "/collections/valentines-day-packages": "/products",
  "/collections/valentines-day-packages.atom": "/products",
  "/pages/see-you-at-kumasi": "/",
  "/pages/tracksuit-sizing": "/size-guide",
  "/product/divine-provision-tee": "/products",
  "/product/kairos-limited-windbreaker-1-5": "/products",
  "/product/sackcloth-v1": "/products?category=Tops",
  "/product/tishbe-motors-tee": "/products?category=Tops",
  "/product/wallpaper-the-one-he-sought": "/products?category=Accessories",
  "/products/acid-wash-sweatshorts": "/product/acid-washed-shorts",
  "/products/acid-washed-shorts-red": "/product/acid-washed-shorts",
  "/products/cream-mothers-smile-x-1nri-collab": "/product/mothers-smile-x-1nri-collab",
  "/products/damaris-bag": "/product/damaris-bag-2",
  "/products/distressed-caps": "/product/distressed-caps",
  "/products/divine-provision-tee": "/products",
  "/products/dry-bones-coffee-brown": "/products?category=Tops&product_type=T-Shirts",
  "/products/dry-bones-tee-white": "/products?category=Tops&product_type=T-Shirts",
  "/products/dusk-before-dawn-button-up": "/products",
  "/products/dusk-before-dawn-button-up-1": "/products",
  "/products/dusk-before-dawn-tee-black": "/products",
  "/products/flare-sweatpants": "/product/flare-sweatpants",
  "/products/flare-sweatpants-grey": "/product/flare-sweatpants",
  "/products/flare-sweatpants-khaki": "/product/flare-sweatpants",
  "/products/flare-sweatpants-navy-blue": "/product/flare-sweatpants",
  "/products/follow-god-coffee-brown": "/products",
  "/products/forever-package": "/products",
  "/products/intercessory-dept-fur-tee-black": "/product/intercessory-dept-black-and-pink",
  "/products/intercessory-dept-hoodie-real-tree": "/product/intercessory-dept-hoodie-real-tree",
  "/products/j-adore-baby-tee-black": "/products",
  "/products/life-and-death-acid-washed-tee": "/products",
  "/products/life-and-death-tee-grey-copy": "/products",
  "/products/maison-de-priere-cyan-blue": "/products",
  "/products/sackcloth-mauve": "/product/sackcloth",
  "/products/sackcloth-obsidian": "/product/sackcloth",
  "/products/shorts": "/products?category=Bottoms&product_type=Shorts",
  "/products/smssend-me-scriptures-tee-black": "/product/sms-send-me-scriptures-tee",
  "/products/varsity-jersey-2-0": "/products?category=Tops",
  "/wpm": "/",
};
